### PR TITLE
Add footer and header/footer oxml registration

### PR DESCRIPTION
**Pull request by North101**
Hi, I needed header/footer support for a project I was working on and I found your branch. Your implementation wasn't complete so I did added what I needed. I haven't cross-checked with the docx spec so please keep that in mind.

Thanks for your work on this, I hope this is of help.

### CODE REVIEW

**Comment by eupharis** [comment]
Awesome! Glad you were able to hack at this to make this do what you want to!

Your use case is to be able to clear content from a header? And add additional sections to a document? Is that so you can have different headers on different sections?

**Comment by North101** [comment]
@eupharis Sort of. I needed to be able to find custom merge tags (including in headers/footers) and replace the content with my own, ignoring styling (my script ignores the styling part).

**Comment by eupharis** [comment]
Cool. Sounds like that functionality should be supported when this feature is finished. Just wanted to make sure :)

 Thanks for this!

**Comment by eupharis** [comment]
@North101 Hey good news @scanny finished support for headers in the main python-docx repo! https://github.com/python-openxml/python-docx

I'm going to go ahead and close this. Hope the main python-docx repo has what you need!

**Pull request closed without merging**
